import Image from "next/image";
import { ArrowUpRight, Github, Linkedin, Mail, MessageCircle } from "lucide-react";
import { ContactForm } from "@/components/contact-form";
import { EducationList } from "@/components/education-list";
import { ProjectFilter } from "@/components/project-filter";
import { getCachedPortfolioContent, type Locale, type SectionKey } from "@/lib/db/queries";
import { copy, localized } from "@/lib/i18n";

type PortfolioContent = Awaited<ReturnType<typeof getCachedPortfolioContent>>;

export function PortfolioSections({ content, locale, settings }: { content: PortfolioContent; locale: Locale; settings: NonNullable<PortfolioContent["settings"]> }) {
  const t = copy[locale];
  const projectCards = content.projects.map((project) => ({ ...project, description: localized(project, "description", locale) }));
  const section = (number: number, key: SectionKey) => {
    if (key === "experience") return <section className="section ruled" id="experiencia" key={key}><header className="sectionHeader"><p className="sectionNumber">{String(number).padStart(2, "0")}</p><div><h2>{t.experience}</h2><p>{t.experienceIntro}</p></div></header><div className="timeline sectionContentOffset">{content.experiences.map((experience) => <article className="timelineItem" key={experience.id}><div className="timelineMeta"><div className="timelineDate">{localized(experience, "date", locale)}</div>{experience.imageUrl && <div className="companyLogo"><Image src={experience.imageUrl} alt={`${experience.company} logo`} width={84} height={84} /></div>}</div><div><p className="kicker">{experience.company}</p><h3>{localized(experience, "role", locale)}</h3><ul>{experience.tasks.map((task) => <li key={task.id}>{localized(task, "text", locale)}</li>)}</ul>{experience.companyUrl && <a className="textLink" href={experience.companyUrl} target="_blank" rel="noreferrer">{experience.company}<ArrowUpRight size={15} /></a>}</div></article>)}</div></section>;
    if (key === "projects") return <section className="section" id="proyectos" key={key}><header className="sectionHeader"><p className="sectionNumber">{String(number).padStart(2, "0")}</p><div><h2>{t.projects}</h2><p>{t.projectsIntro}</p></div></header><div className="sectionContentOffset"><ProjectFilter projects={projectCards} locale={locale} /></div></section>;
    if (key === "technologies") return <section className="section stackSection" id="stack" key={key}><header className="sectionHeader"><p className="sectionNumber">{String(number).padStart(2, "0")}</p><div><h2>{t.stack}</h2></div></header><div className="techGrid">{content.technologies.map((technology) => <article key={technology.id} className="techItem">{technology.imageUrl && <Image src={technology.imageUrl} alt="" width={44} height={44} />}<div><h3>{technology.name}</h3><p>{localized(technology, "category", locale)}</p></div></article>)}</div></section>;
    if (key === "education") return <section className="section ruled" id="formacion" key={key}><header className="sectionHeader"><p className="sectionNumber">{String(number).padStart(2, "0")}</p><div><h2>{t.education}</h2></div></header><EducationList hasMore={content.education.length > 5} loadMoreLabel={t.loadMoreEducation}>{content.education.map((item) => <article key={item.id}><p className="educationDate">{localized(item, "date", locale)}</p><div className="educationTitleRow">{item.imageUrl && <div className="educationLogo"><Image src={item.imageUrl} alt={`${item.institution} logo`} width={58} height={58} /></div>}<div><h3>{localized(item, "title", locale)}</h3><p className="kicker">{item.institution}</p></div></div>{localized(item, "detail", locale) && <p>{localized(item, "detail", locale)}</p>}</article>)}</EducationList></section>;
    if (key === "personal") return <section className="section personalSection" id="personal" key={key}><header className="sectionHeader"><p className="sectionNumber">{String(number).padStart(2, "0")}</p><div><h2>{t.personal}</h2></div></header><div className="personalGrid sectionContentOffset">{(["language", "hobby"] as const).map((type) => <div key={type}><p className="kicker">{type === "language" ? t.languages : t.hobbies}</p>{content.personalItems.filter((item) => item.type === type).map((item) => <div className="personalItem" key={item.id}><h3>{localized(item, "label", locale)}</h3><p>{localized(item, "detail", locale)}</p></div>)}</div>)}</div></section>;
    return <section className="contactSection" id="contacto" key={key}><div className="contactCopy"><p className="sectionNumber">{String(number).padStart(2, "0")}</p><h2>{t.contact}</h2><p>{t.contactIntro}</p><div className="socialLinks"><a href={`mailto:${settings.email}`}><Mail size={18} />{settings.email}</a><a href={settings.linkedinUrl} target="_blank" rel="noreferrer"><Linkedin size={18} />LinkedIn</a><a href={settings.githubUrl} target="_blank" rel="noreferrer"><Github size={18} />GitHub</a><a href={settings.whatsappUrl} target="_blank" rel="noreferrer"><MessageCircle size={18} />WhatsApp</a></div></div><ContactForm locale={locale} /></section>;
  };
  return <>{content.sectionOrder.map((key, index) => section(index + 1, key))}</>;
}
